trigger: none

variables:
- name: env
  value: pocjson


pool: SamplePool

stages:
  - stage: azurescript
    jobs:
      - job:
        steps:
          # - task: AzureCLI@2
          #   inputs:
          #     azureSubscription: 'Visual Studio Professional Subscription(36e17b0a-f140-42b7-933a-03495cc621b2)'
          #     scriptType: 'ps'
          #     scriptLocation: 'inlineScript'
          #     inlineScript: |
          #       az group list --query "[?tags.env=='business']" | ConvertFrom-Json | add-content "C:\Users\A888382\Documents\Testing1\test.txt"
                             
    
      
          # - task: AzureCLI@2
          #   inputs:
          #     azureSubscription: 'Visual Studio Professional Subscription(36e17b0a-f140-42b7-933a-03495cc621b2)'
          #     scriptType: 'ps'
          #     scriptLocation: 'inlineScript'
          #     inlineScript: |
          #       $result1 = $(az appservice plan list --query "[?tags.env=='prod' && tags.owner=='adinath']" | ConvertFrom-Json)
          #       $res = $result1.resourceGroup
          #       write-output $res


          - task: AzureCLI@2
            inputs:
              azureSubscription: 'Visual Studio Professional Subscription(36e17b0a-f140-42b7-933a-03495cc621b2)'
              scriptType: 'ps'
              scriptLocation: 'inlineScript'
              inlineScript: | 
                $appservicePlan = $(az appservice plan list --query "[?tags.env=='$env' && tags.owner=='adinath']" | ConvertFrom-Json)
                write-output $appservicePlan
                $fileName = "C:\Users\A888382\Documents\Testing1\terraform.tfvars.json"

                $data = Get-Content -path $fileName -Raw | ConvertFrom-Json

                # $result11 = $appservicePlan.name
                $data.plan_name = $appservicePlan.name

                # $result22 = $appservicePlan.resourceGroup
                $data.resource_group_name = $appservicePlan.resourceGroup

                $data.location = $appservicePlan.location

                $data.env = $(env)

                $data.apps.app.app_name = "appservice"

                $data | ConvertTo-Json | set-content -Path $fileName
          - task: AzureCLI@2
            inputs:
              azureSubscription: 'Visual Studio Professional Subscription(36e17b0a-f140-42b7-933a-03495cc621b2)'
              scriptType: 'ps'
              scriptLocation: 'inlineScript'
              inlineScript: |
                $fileName1 = "C:\Users\A888382\Documents\Testing1\terraform1.tfvars.json"
                $data1 = Get-Content -path $fileName1 -Raw | ConvertFrom-Json 

                $resourcegroup = $(az group list --query "[?tags.env== $env1]" | ConvertFrom-Json)
                $data1.resource_group_name = $resourcegroup.name
                $rgname1 = $resourcegroup.name

                write-output $rgname1

                $appserviceplan = $(az appservice plan list --query "[?resourceGroup=='$resourcegroup']" | ConvertFrom-Json)
                $data1.plan_name = $appserviceplan.name
                $planname = $appserviceplan.name
                
                write-output $planname

                $data1 | ConvertTo-Json | set-content -Path $fileName1

                # az appservice plan show --name $planname --resource-group $rgname1 --query '{rname:resourceGroup, pname:name}' -o json | add-content "C:\Users\A888382\Documents\Testing1\terraform.tfvars.json"
            
  # - template: ../templates/terraform-deploy.yml
  #   parameters:
  #     environment: ${{ variables.env }}
  #     working_dir: "$(Build.SourcesDirectory)/POCJson/env"
  #     serviceconn_name : "svc-poc2"
  #     tfresourcegroupname : "config-demo2"
  #     tfstorageaccountname : "globalstorageac"
  #     azureRmContainerName : "globalstoragecon2"
  #     tfstatefile : "terraform-tfstate.tfstate"
