trigger: none

variables:
- name: env
  value: pocjson
- name: res
  value: "poconjson"

pool: SamplePool

stages:
  - stage: azurescript
    jobs:
      - job:
        steps:
          # - task: AzureCLI@2
          #   inputs:
          #     azureSubscription: 'Visual Studio Professional Subscription(36e17b0a-f140-42b7-933a-03495cc621b2)'
          #     scriptType: 'ps'
          #     scriptLocation: 'inlineScript'
          #     inlineScript: |
          #       az group list --query "[?tags.env=='business']" | ConvertFrom-Json | add-content "C:\Users\A888382\Documents\Testing1\test.txt"
                             
          # - task: AzureCLI@2
          #   inputs:
          #     azureSubscription: 'Visual Studio Professional Subscription(36e17b0a-f140-42b7-933a-03495cc621b2)'
          #     scriptType: 'ps'
          #     scriptLocation: 'inlineScript'
          #     inlineScript: |
          #       az group list --query "[?tags.env=='business']" | ConvertFrom-Json | add-content "C:\Users\A888382\Documents\Testing1\test.txt"
          

      
          - task: AzureCLI@2
            inputs:
              azureSubscription: 'Visual Studio Professional Subscription(36e17b0a-f140-42b7-933a-03495cc621b2)'
              scriptType: 'ps'
              scriptLocation: 'inlineScript'
              inlineScript: |
                $result1 = $(az appservice plan list --query "[?tags.env=='prod' && tags.owner=='adinath']" | ConvertFrom-Json)
                $res = $result1.resourceGroup
                write-output $res

          - task: AzureCLI@2
            inputs:
              azureSubscription: 'Visual Studio Professional Subscription(36e17b0a-f140-42b7-933a-03495cc621b2)'
              scriptType: 'ps'
              scriptLocation: 'inlineScript'
              inlineScript: az appservice plan list --resource-group $res

          - task: AzureCLI@2
            inputs:
              azureSubscription: 'Visual Studio Professional Subscription(36e17b0a-f140-42b7-933a-03495cc621b2)'
              scriptType: 'ps'
              scriptLocation: 'inlineScript'
              inlineScript: az appservice plan list --query "[?resourceGroup=='$res']"
              
          # - task: AzureCLI@2
          #   inputs:
          #     azureSubscription: 'Visual Studio Professional Subscription(36e17b0a-f140-42b7-933a-03495cc621b2)'
          #     scriptType: 'ps'
          #     scriptLocation: 'inlineScript'
          #     inlineScript: |
          #       $result2 = $(az group list --query "[?tags.env=='business']" | ConvertFrom-Json)
          #       $rgname1 = $result2.name
          #       write-output $rgname1

  # - template: ../templates/terraform-deploy.yml
  #   parameters:
  #     environment: ${{ variables.env }}
  #     working_dir: "$(Build.SourcesDirectory)/POCJson/env"
  #     serviceconn_name : "svc-poc2"
  #     tfresourcegroupname : "config-demo2"
  #     tfstorageaccountname : "globalstorageac"
  #     azureRmContainerName : "globalstoragecon2"
  #     tfstatefile : "terraform-tfstate.tfstate"
