trigger: none

pool: SamplePool

variables:
- name: env
  value: pocjson

stages:
  - template: ./templates/terraform-deploy.yml
    parameters:
      environment: ${{ variables.env }}
      working_dir: "$(Build.SourcesDirectory)/POCJson/env"
      serviceconn_name : "svc-poc2"
      tfresourcegroupname : "config-demo2"
      tfstorageaccountname : "globalstorageac"
      azureRmContainerName : "globalstoragecon2"
      tfstatefile : "terraform-tfstate.tfstate"
