trigger: none

pool: SamplePool

variables:
- name: env
  value: pocjson



stages:
  - stage: azurescript
    jobs:
      - job:
        steps:
      
          - task: AzureCLI@2
            inputs:
              azureSubscription: 'Visual Studio Professional Subscription(36e17b0a-f140-42b7-933a-03495cc621b2)'
              scriptType: 'ps'
              scriptLocation: 'inlineScript'
              inlineScript: az group list --query "[?location=='eastus']" --output table --output json
               
          # - task: AzureCLI@2
          #   displayName: Azure CLI
          #   inputs:
          #     azureSubscription: 'Visual Studio Professional Subscription(36e17b0a-f140-42b7-933a-03495cc621b2)'
          #     scriptType: ps
          #     scriptLocation: inlineScript
          #     inlineScript: |
          #       az --version
          #       az account show

          # - task: AzureCLI@2
          #   inputs:
          #     azureSubscription: 'Visual Studio Professional Subscription(36e17b0a-f140-42b7-933a-03495cc621b2)'
          #     scriptType: 'ps'
          #     scriptLocation: 'inlineScript'
          #     inlineScript: |
          #       $result=$('az group list --query "[?location==''eastus'']" --output table') 
          #       $result

  - template: ../templates/terraform-deploy.yml
    parameters:
      environment: ${{ variables.env }}
      working_dir: "$(Build.SourcesDirectory)/POCJson/env"
      serviceconn_name : "svc-poc2"
      tfresourcegroupname : "config-demo2"
      tfstorageaccountname : "globalstorageac"
      azureRmContainerName : "globalstoragecon2"
      tfstatefile : "terraform-tfstate.tfstate"
